version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "Dependencies: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "Dependencies: "
